### ISSUE TITLE
Question : Sensor scale for proximity

### ISSUE THREAD

**Issue by jorgevinagre** [pimoroni/ltr559-python#3]
Hello

Just wanted to ask what is the scale for proximity sensor. The max value is around 2050 but it´s measured in what units?

Thanks

**Comment by Gadgetoid** [comment]
The datasheet isn't especially clear on this- the proximity sensor is an emitter/receiver pair which, presumably, measures a reflected lux value from the proximal surface.

The datasheet specifies the unit for the ADC as "count" which *may* refer to a count of the number of LED pulses emitted and then subsequently detected in a given timespan, or it may be an absolute reflected lux value (with presumably some smoothing).

I don't think it maps proportionally to distance (or any meaningful unit), but I haven't conducted any tests to verify this. If it's a measurement of reflected light then the value should - in theory - be possible to translate (approximately) into distance using the inverse square law.

I'd wager that testing against a set of expected detection objects at your desired detection distances and deriving a formula or threshold from the results would be far easier, though. And potentially more accurate, since I don't think any formula could apply generally here across a full range of object reflectiveness.

To set expectations- I think the purpose of this sensor is more to determine "is something covering the sensor" than "is something 10mm from the sensor." It's the sort of package you might find in the top of a smartphone to compensate for ambient light and turn off the touch input/screen when a face is up against it.

**Comment by jorgevinagre** [comment]
Hi

I didn´t expect such a complete answer and it´s very clear, so I thank you.

Keep the excelent work at Pimoroni
