### ISSUE TITLE
Lux Value

### ISSUE THREAD

**Issue by pssc** [pimoroni/ltr559-python#4]
Lux value seems high compared to a vcnl4010

17:12:50 ltr559/vcnl4010 Lux: 1722.14/209.75, Proximity: 0000/2193

Appendix A for the datasheet is missing from the website so there are no detail of the lux calculation for the chip.

**Comment by Gadgetoid** [comment]
There's code for the Lux calculation here which seems to disagree with what we're doing in this library, but no way of verifying if it's any more correct:

https://github.com/TeamWin/android_kernel_kazam_thunder_q45/blob/95b1263fbe48c589ba935d7ad2efb523c2b54fc1/mediatek/custom/common/kernel/alsps/ltr559/ltr559.c#L773-L789

A key factor seems to be the use of the gain range to divide the result of the lux calculation.

What gain are you using with the LTR-559? `1722.14` seems conveniently close to 8x 209.75.

**Comment by pssc** [comment]
Good find @Gadgetoid 

I was using the default which is 4x but issues persist having tested with 1x, there seems to adjustment for lux calculation  due to changes in gain, just ratio changes between the two channel readings in this library.

I am not sure the divisors are all correct for my current gain possibly a power of 10 out.

**Comment by pssc** [comment]
@Gadgetoid so a quick hack to the library and I have the numbers generated by the C code equivalent in the python lib closer to the VNCL4010, seems to be a constant delta at this ratio

als0  663 als1  577
ratio  46.53225806451613 gainrange 4
16:58:08 ltr559/vcnl4010 Lux: 427.18/280.50, Proximity: 0000/2179

I haven't got a Adafruit VEML7700 for reference which does all this jazz for you but the calculation for the VNCL4010 is quite simple.

**Comment by pssc** [comment]
Ok so its a lot better based on the code its still a bit iffy around those threshold transistions
![Lux-2019-05-17](https://user-images.githubusercontent.com/1763553/57941963-3638df80-78c8-11e9-9b5e-1679b59c9bb9.png)

@Gadgetoid any chance of that reference documentation?  i will work up a minimal pull request with what I have as its an improvement, assuming the VCNL4010 is correct, I will probably get a VEML at some point for ref but not this month...

**Comment by pssc** [comment]
![2019-05-19](https://user-images.githubusercontent.com/1763553/57975818-7338cb00-79c9-11e9-9379-724460d450c2.png)
So we can see from the last days data we are better but the is a small delta and it look like from my data the ratio thresholds for the calculation look to be flawed, specifically the one set at 45 may be better at 43.

@Gadgetoid I have refactored the code for a minimal patch and have tweaked the ratio thresholds based on my experimental data, we shall see what tomorrow brings.

**Comment by pssc** [comment]
![2019-05-19 end](https://user-images.githubusercontent.com/1763553/57988914-9a57d100-7a8b-11e9-84cb-af0396f5a98d.png)

OK so things are looking better after further tweaking of ratio thresholds and multiplier values for the lux calculation, all this has been done with a gain of 4 so far so will need to test others...

Also still need an alternate reference other then the vcnl4010, all the work so far assumes that this is a good reference.

It looks like the ltr-5559 gives up below ~1.5lx (Twilight 1lx) tested with gain of up to x96 no joy 👎 
seems to be a fair amount of jitter in the lux calculation also :(

**Comment by pssc** [comment]
ok @Gadgetoid looking at what we have a may be able to make the library produce a reliable lux reading for 1 gain setting and integration time combo but that missing appendix A from the Data sheet would be really useful. Any contact be made with LightOn?

**Comment by pssc** [comment]
@Gadgetoid I have had a very prompt response from LiteOn and now can work a proper patch based on their recommended calculation

**Comment by pssc** [comment]
@Gadgetoid ok implemented a per appendix A and the _lux values are just substantially different to the vcnl4010  will post graph once its been running a while, this leaves 2 possibilities the vcnl4010 is wrong or the ltr559 is wrong(or the calculation  supplied is)... 

Given when you change the gain and or the measurement time of the lux value of the ltr559 changes in the same light conditions, my money is on the ltr559

**Comment by Gadgetoid** [comment]
Oh wow! You've been busy. That's awesome, thank you!

I find a lot of these sensors have very difficult output values to reason about- in the case of the ltr559 I think the chip is designed for ambient light compensation and up to this point I suspect nobody has cared about getting accurate Lux readings out of it.

You've given this far more time and attention than I could possibly hope to do at the moment- given that it seems impossible to make the ltr559 output comparable values, should we leave it as is, or switch to their compensation formula? What's your verdict?

**Comment by RLovelett** [comment]
@pssc is there any chance of you posting the Appendix A or the patch (or both)?

**Comment by pssc** [comment]
> @pssc is there any chance of you posting the Appendix A or the patch (or both)?

@RLovelett working on it I have a patch using the algorithm defined, I will try push this before the weekend in probably needs some else to test? but well results are still dubious, I am working on the recommended gain and integration time selection to see if that produces a more reliable reading, as well as a calibrated lux meter to test against, as the ltr559 ,vcnl4010 & vmel7700 all produce different readings usually +- at least 50-200lx in normal conditions!

This may be a little while has the hassio box providing my graphing seems to have eaten itself again.

Appendix A is copyright LightOn so that is up to them to publish.

**Comment by RLovelett** [comment]
> Appendix A is copyright LightOn so that is up to them to publish.

Fair enough I've made a request on their contact form :crossed_fingers: I get a copy too.

Thanks for the feedback. I'm very interested to see what you come up with.

**Comment by pssc** [comment]
> > Appendix A is copyright LightOn so that is up to them to publish.
> 
> Fair enough I've made a request on their contact form 🤞 I get a copy too.
> 
> Thanks for the feedback. I'm very interested to see what you come up with.

@RLovelett ok have a look in my forked repo, if you want to test that would be good, then if all is ok well send in a PR.

**Comment by RLovelett** [comment]
Last night I got everything running and the data seemed smoother and less susceptible to large flucuations in output lux value. Especially in low light. I'm going to hook the sensor up to write some data to a file for 24 hours to plot it. But my initial impression is good.

BTW is there a phone number or e-mail address you can recommend for contacting LiteOn to get Appendix A for myself? I didn't get any response from them about my request.

**Comment by RLovelett** [comment]
Alright, here's what I have from a little over one hours worth of data.

![lux-algos](https://user-images.githubusercontent.com/335572/60355747-27504d00-999d-11e9-8d11-b05158fc14e0.png)

It seems, more or less, this new change is effectively the same change as what is in the [Android kernel link from above](https://github.com/TeamWin/android_kernel_kazam_thunder_q45/blob/95b1263fbe48c589ba935d7ad2efb523c2b54fc1/mediatek/custom/common/kernel/alsps/ltr559/ltr559.c#L773-L789) with just some sort of 2x multiplier on it.

Also, you can see that the current algorithm, `ltr559_pthon`, has interesting characteristics with regard to the other two.

1. It is much higher in magnitude. (I think this is due to the gain factor being wrong/hard coded).
2. It seems to follow channel 1 a little bit more than the "new" algorithms do.

Intuitively the `ltr559_python` feels like the curve that matches my experience sitting in the room with the sensor running. I'm sitting next to a east facing window as the sun has risen the room has gotten noticeably brighter. The `ltr559_python` line has trended upwards accordingly. However, the other two have largely stayed flat. This gives me the feeling that something isn't quite right. Indeed, quick searching of the internet a "normal" lux value near a window indoors on a clear day might be on the order of 100-300 lux. The original algorithm is providing near ~170 and it's an overcast day here.

It's worth noting that I have "ported" this code from Python into Node. So it is well within reason that I've botched something in the porting. To help thwart this I'm collecting `ch0` and `ch1` values as well (as you can see in the plot). Just to make sure that if something is wrong with the algorithms I can "replay" the lux calculation again without having to re-collect.

The source data file for the plot is [here](https://github.com/pimoroni/ltr559-python/files/3340040/2019-06-28T14.20.46.247Z.txt).

**Comment by RLovelett** [comment]
@pssc I have a suggestion.

If you make this change

```patch
diff --git a/library/ltr559/__init__.py b/library/ltr559/__init__.py
index eaa8120..6879ff1 100644
--- a/library/ltr559/__init__.py
+++ b/library/ltr559/__init__.py
@@ -435,7 +435,7 @@ def update_sensor():
             _als0 = ALS_DATA.get_ch0()
             _als1 = ALS_DATA.get_ch1()
 
-        _ratio = _als1 * 100 / (_als1 + _als0) if _als0 + _als1 > 0 else 101
+        _ratio = _als0 * 100 / (_als1 + _als0) if _als0 + _als1 > 0 else 101
         if _ratio < 45:
            ch_idx = 0
         elif _ratio < 64:
```

The the plot goes from the purple `pssc` to the green `pssc_inverted`.

![lux-algos-inverted](https://user-images.githubusercontent.com/335572/60359560-5b307000-99a7-11e9-9ae5-2b08c6372809.png)

Without being able to see Appendix A I'm not 100% sure if that is the only change necessary but it now seems to at least track the upwards trend of brightness in the room.

**Comment by pssc** [comment]
@RLovelett if your sub 100 counts on the sensor try upping the gain...

**Comment by Gadgetoid** [comment]
Thanks @pssc for this changeset which fixes lux compensation across the various gain. A quick test of this yields much more sensible values than the code prior to this change, albeit the lux values are still quite varied - https://github.com/pimoroni/ltr559-python/pull/5

Since the LTR559 is an uncalibrated bare light sensor I suspect some of this is par for the course, but I'm always eager to hear any improvements that could be made to the library and/or examples to set expectations better or produce more consistent output data.

**Comment by Gadgetoid** [comment]
Closing this issue for now, feel free to re-open if you're still encountering issues. Thank you to everyone involved. It's much appreciated!
