### ISSUE TITLE
proximity interrupt

### ISSUE THREAD

**Issue by Eirikur** [pimoroni/ltr559-python#6]
I'm trying to use this. There's no example, but I'm reading the code for the library. This support seems incomplete to me because there's no way to specify a callback or anything like that. Am I missing something? I really like the Enviro+ hat.

Eirikur

**Comment by Gadgetoid** [comment]
I've managed to get this up and running locally- there were some bugs in the library and some salient points in the datasheet regarding enabling interrupts before the sensors themselves.

I'm in the process of adding this functionality and an accompanying example in PR #7

**Comment by Eirikur** [comment]
Wow, you did a better job reading the data sheet than I did. Do you know what this interrupt is actually supposed to do?  I expected a call-back or something like that, but I don't think that is what the feature is meant for....but I didn't understand that part of the datasheet. I'm a developer. I should be able to understand a datasheet!

**Comment by Gadgetoid** [comment]
Effectively all the interrupt does is flip a bit in a register somewhere on the sensor. The interrupt settings allow the state of this bit to be output to a hardware pin, which is useful since it's much less costly to check a hardware pin (on the Pi it can be a cheap and direct as reading a memory address) than run an i2c transaction to request the register state from the sensor.

On microcontrollers this may be used to save power by sleeping the micro and waking on external interrupt. On the Pi... not so much!

The only way to have a function trigger on interrupt is to do it yourself, which effectively boils down to polling the GPIO pin and running some Python when it changes state. `RPi.GPIO` will do this for you and that's what this portion of code is doing:

```python
def interrupt_handler(pin):
    int_als, int_ps = ltr559.get_interrupt()
    if int_ps:
        print("Proximity interrupt: {}".format(ltr559.get_proximity()))

GPIO.add_event_detect(4, callback=interrupt_handler, edge=GPIO.FALLING)
```

I should probably add a description of all this to the example, since it may prove useful for someone from the software world getting into hardware (the path I took myself, as it happens!)

**Comment by Eirikur** [comment]
Thanks so much for working on this. The proximity interrupt example never triggers for me. The proximity and light example shows expected changing proximity values.  I have two enviro+ hats and I'm running on a Pi2B, but I have Pi 4s as well. I can read proximity values from my own program. I'd like to get interrupts working. I mention that I have two of the hats because I was wondering if there could be a hardware problem on one, but no, I get the same results on both.

**Comment by Gadgetoid** [comment]
A quick check over the schematic confirms that the interrupt line is not wired on the Enviro+, which would certainly suggest why it's not triggering. It was probably omitted since this is an environmental sensor package that's going to be polled anyway. Doesn't even look possible to bodge that connection on, since the pads are hidden underneath the sensor. Sorry!

**Comment by Eirikur** [comment]
Thanks anyway!
